stages:
  - validate
  - deploy

variables:
  SNAPLOGIC_BASE_URL: "https://cdn.elastic.snaplogic.com"
  SNAPLOGIC_ORG: "Parters"
  SNAPLOGIC_PROJECT: "Nihilent/CICD-Dev1"
  SNAPLOGIC_ENV: "test"  # Specify environment (e.g., test, prod)
  SNAPLOGIC_USERNAME: "$SNAPLOGIC_USERNAME"  # Username from CI/CD secrets
  SNAPLOGIC_PASSWORD: "$SNAPLOGIC_PASSWORD"  # Password from CI/CD secrets
  SNAPLOGIC_AUTH_TOKEN: ""  # Placeholder for auth token

validate:
  stage: validate
  script:
    - echo "Validating SnapLogic pipelines..."
    - python scripts/validate_snaplogic_assets.py  # Custom script for validation.

deploy:
  stage: deploy
  script:
    - echo "Authenticating with SnapLogic..."
    - export SNAPLOGIC_AUTH_TOKEN=$(curl -s -X POST "${SNAPLOGIC_BASE_URL}/api/1/rest/sls/auth/token" \
        -d "username=${SNAPLOGIC_USERNAME}&password=${SNAPLOGIC_PASSWORD}" | jq -r '.access_token')

    - echo "Deploying SnapLogic assets to test environment..."
    - python scripts/deploy_snaplogic_assets.py --auth-token $SNAPLOGIC_AUTH_TOKEN --base-url $SNAPLOGIC_BASE_URL --org $SNAPLOGIC_ORG --project $SNAPLOGIC_PROJECT --env $SNAPLOGIC_ENV

