name: Deploy SnapLogic to Test Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests jq

      - name: Authenticate with SnapLogic
        id: authenticate
        run: |
          AUTH_TOKEN=$(curl -s -X POST "${{ secrets.SNAPLOGIC_BASE_URL }}/api/1/rest/sls/auth/token" \
          -d "username=${{ secrets.SNAPLOGIC_USERNAME }}&password=${{ secrets.SNAPLOGIC_PASSWORD }}" | jq -r '.access_token')
          echo "AUTH_TOKEN=$AUTH_TOKEN" >> $GITHUB_ENV

      - name: Deploy SnapLogic Pipelines
        run: |
          python scripts/deploy_snaplogic_assets.py \
          --auth-token $AUTH_TOKEN \
          --base-url ${{ secrets.SNAPLOGIC_BASE_URL }} \
          --org ${{ secrets.SNAPLOGIC_ORG }} \
          --project ${{ secrets.SNAPLOGIC_PROJECT }} \
          --env test
